# Generated by Django 3.2.3 on 2021-06-29 19:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Email address of user', max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description of project', max_length=100)),
                ('url', models.URLField(help_text='URL to project')),
                ('summary', models.TextField(blank=True, help_text='Short summary describing project', null=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of skill, language or framework', max_length=100)),
                ('confidence', models.FloatField(help_text='Apprximate confidence rating of skill', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)])),
                ('icon', models.CharField(blank=True, help_text='Font awesome icon', max_length=50, null=True)),
                ('example', models.ForeignKey(blank=True, help_text='Related project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill', to='users.project')),
                ('user', models.ForeignKey(help_text='Users skills', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name of user', max_length=50)),
                ('last_name', models.CharField(help_text='Last name (surname) of user', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, help_text='Users data of birth', null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact number where user can be reached', max_length=128, null=True, region=None)),
                ('email_address', models.EmailField(help_text='Email address of user', max_length=50)),
                ('city', models.CharField(help_text='City where user currently resides', max_length=50)),
                ('country', models.CharField(help_text='Country where user currently resides', max_length=50)),
                ('summary', models.TextField(help_text='Short summary describing user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Link name', max_length=100)),
                ('url', models.URLField(help_text='Link')),
                ('user', models.ForeignKey(help_text='User links', on_delete=django.db.models.deletion.CASCADE, related_name='link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Official position name in company', max_length=50)),
                ('company', models.CharField(help_text='Name of company', max_length=50)),
                ('country', models.CharField(help_text='Country where job resided', max_length=50)),
                ('summary', models.TextField(help_text='Short summary of experience and responsibilities')),
                ('start_date', models.DateField(help_text='Approximate start date of job')),
                ('end_date', models.DateField(blank=True, help_text='Approximate end date of job', null=True)),
                ('user', models.ForeignKey(help_text='Users experience', on_delete=django.db.models.deletion.CASCADE, related_name='experience', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='Name of degree', max_length=50)),
                ('university', models.CharField(help_text='Name of university where student got degree', max_length=50)),
                ('country', models.CharField(help_text='Country where degree was given', max_length=50)),
                ('summary', models.TextField(blank=True, help_text='Short summary of experience and skills learned during degree', null=True)),
                ('start_date', models.DateField(blank=True, help_text='Approximate start date of degree', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Approximate end date of degree', null=True)),
                ('example', models.ForeignKey(blank=True, help_text='Related project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='users.project')),
                ('user', models.ForeignKey(help_text='Users education', on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
            },
        ),
    ]
