version: "3"

services:
  portfolio:
    container_name: portfolio
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8080"

    environment:
      DJANGO_DEBUG: 'True'
      DATABASE_PASS: "root"
      DATABASE_USER: "root"
      DATABASE_NAME: "portfolio"
      DATABASE_HOST: "sql"
      HASHID_FIELD_SALT: "${HASHID_FIELD_SALT}"
      SECRET_KEY: "${SECRET_KEY}"
    volumes:
      - .:/home/portfolio
    ports:
      - "8081:8080"
    networks:
      - portfolio_network
    depends_on:
      - sql

  sql:
    container_name: sql
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: portfolio
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - portfolio_network

volumes:
  mysql_volume:

networks:
  portfolio_network:
    external: true
